import * as XLSX from "xlsx";

// Reads Sandip's finished Outstanding Tracker workbook exactly as it sits —
// no arithmetic anywhere. Totals in the summary block are whatever value his
// Excel had saved in those cells. Layout is found by landmarks, not fixed
// row numbers, because his sheet's month columns (and how many party rows
// are filled) change from one upload to the next:
//   - title / "As on …" line   = the first two non-empty lines at the top
//   - table header row          = the row whose first cell is "Sr. No."
//   - summary block             = the label row + value row just above it
//   - party rows                = everything below the header with any data
//                                 beyond the Sr. No. (pre-numbered blank
//                                 rows are dropped)

export type Cell = string | number | null;

export interface ParsedOutstanding {
  title: string;
  asOnLabel: string;
  asOnDate: Date | null;
  summary: { label: string; value: Cell }[];
  columns: string[];
  rows: Cell[][];
  warnings: string[];
}

function clean(v: unknown): Cell {
  if (v === null || v === undefined) return null;
  if (typeof v === "number") return v;
  const s = String(v).replace(/\s+/g, " ").trim();
  return s === "" ? null : s;
}

const MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];

function parseAsOn(label: string): Date | null {
  const m = label.match(/(\d{1,2})[-\s/.]+([A-Za-z]{3,9})[-\s/.,]+(\d{4})/);
  if (!m) return null;
  const mi = MONTHS.indexOf(m[2].slice(0, 3).toLowerCase());
  if (mi < 0) return null;
  return new Date(Date.UTC(Number(m[3]), mi, Number(m[1])));
}

export function parseOutstandingWorkbook(buf: Buffer): ParsedOutstanding {
  const wb = XLSX.read(buf, { type: "buffer", cellFormula: true, cellDates: false });
  const ws = wb.Sheets[wb.SheetNames[0]];
  if (!ws) throw new Error("The file has no sheets");
  const grid: unknown[][] = XLSX.utils.sheet_to_json(ws, { header: 1, raw: true, defval: "" });

  const headerIdx = grid.findIndex((r) => String(r[0] ?? "").toLowerCase().replace(/[\s.]/g, "") === "srno");
  if (headerIdx < 0) throw new Error('Could not find the table header row (a row starting with "Sr. No.")');

  const headerRow = grid[headerIdx].map((v) => {
    const c = clean(v);
    return c == null ? "" : String(c);
  });
  let lastCol = headerRow.length - 1;
  while (lastCol > 0 && headerRow[lastCol] === "") lastCol--;
  const columns = headerRow.slice(0, lastCol + 1);

  const rows: Cell[][] = [];
  for (let r = headerIdx + 1; r < grid.length; r++) {
    const cells = columns.map((_, c) => clean(grid[r][c]));
    if (cells.slice(1).some((v) => v !== null)) rows.push(cells);
  }

  // Title + "As on" line: first two non-empty lines above the summary block.
  const topLines: string[] = [];
  for (let r = 0; r < headerIdx && topLines.length < 2; r++) {
    const first = grid[r].map(clean).find((v) => v !== null);
    if (typeof first === "string") topLines.push(first);
    else if (first != null) break;
  }
  const title = topLines[0] ?? "";
  const asOnLabel = topLines.find((l) => /as on/i.test(l)) ?? "";

  // Summary block: last non-empty row above the header = values, the row
  // above that = labels.
  const summary: { label: string; value: Cell }[] = [];
  let valueRow = headerIdx - 1;
  while (valueRow >= 0 && !grid[valueRow].some((v) => clean(v) !== null)) valueRow--;
  if (valueRow >= 1) {
    const labelRow = grid[valueRow - 1];
    labelRow.forEach((lab, c) => {
      const l = clean(lab);
      if (typeof l === "string") summary.push({ label: l, value: clean(grid[valueRow][c]) });
    });
  }

  // Formulas saved without a cached result (file generated by a script and
  // never opened/saved in Excel) would come through blank — say so rather
  // than silently showing empty totals.
  const warnings: string[] = [];
  let uncached = 0;
  for (const addr of Object.keys(ws)) {
    if (addr[0] === "!") continue;
    const cell = ws[addr] as XLSX.CellObject;
    if (cell.f && (cell.v === undefined || cell.v === null)) uncached++;
  }
  if (uncached > 0) {
    warnings.push(`${uncached} formula cell(s) have no saved value — open the file in Excel, save it, and upload again; those cells show blank.`);
  }

  return { title, asOnLabel, asOnDate: parseAsOn(asOnLabel), summary, columns, rows, warnings };
}
